# Generated by Django 2.2.1 on 2019-07-11 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], default='none', max_length=7)),
                ('lproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsed_product', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='toppingamount',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='toppingamount',
            name='topping',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='ToppingAmount',
        ),
        migrations.AddField(
            model_name='product',
            name='response',
            field=models.ManyToManyField(blank=True, related_name='user_response', through='products.Response', to=settings.AUTH_USER_MODEL),
        ),
    ]
