# Generated by Django 2.2.1 on 2019-07-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190712_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pub_date']},
        ),
    ]
