# Generated by Django 2.2.1 on 2019-07-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190714_0711'),
        ('products', '0002_auto_20190705_0206'),
    ]

    operations = [
    ]
